# Generated by Django 3.2.16 on 2022-10-11 03:51

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('capacity',
                 models.IntegerField(validators=[transactions.models.validate_capacity], verbose_name='Capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('day', models.DateField(verbose_name='Event Day')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_public', models.BooleanField()),
                ('customers', models.ManyToManyField(to='transactions.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
